import type { CSSProperties } from "react";

export const pinInputStyles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: "#ffffff",
    minWidth: "280px",
  },
  header: {
    textAlign: "center" as const,
    marginBottom: "32px",
  },
  title: {
    fontSize: "20px",
    fontWeight: 600,
    margin: "0 0 8px 0",
    color: "#ffffff",
  },
  subtitle: {
    fontSize: "14px",
    color: "rgba(255, 255, 255, 0.6)",
    margin: 0,
  },
  hiddenInput: {
    position: "absolute" as const,
    opacity: 0,
    pointerEvents: "none" as const,
  },
  dotsContainer: {
    display: "flex",
    gap: "16px",
    marginBottom: "32px",
    cursor: "pointer",
  },
  dotsContainerShake: {
    animation: "tonpay-pin-shake 0.5s ease-in-out",
  },
  dot: {
    width: "14px",
    height: "14px",
    borderRadius: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    border: "2px solid rgba(255, 255, 255, 0.3)",
    transition: "all 0.15s ease",
  },
  dotFilled: {
    backgroundColor: "#0098EA",
    borderColor: "#0098EA",
    transform: "scale(1.1)",
  },
  dotLoading: {
    animation: "tonpay-pin-pulse 1s ease-in-out infinite",
  },
  error: {
    fontSize: "14px",
    color: "#FF5252",
    margin: "-16px 0 24px 0",
    textAlign: "center" as const,
  },
  keypad: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "8px",
    width: "100%",
    maxWidth: "260px",
  },
  keypadButton: {
    width: "72px",
    height: "56px",
    fontSize: "24px",
    fontWeight: 500,
    color: "#ffffff",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  keypadButtonEmpty: {
    width: "72px",
    height: "56px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  biometricButton: {
    width: "56px",
    height: "56px",
    fontSize: "24px",
    color: "#0098EA",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  backspaceButton: {
    width: "72px",
    height: "56px",
    fontSize: "24px",
    color: "rgba(255, 255, 255, 0.6)",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButton: {
    marginTop: "24px",
    padding: "12px 32px",
    fontSize: "16px",
    fontWeight: 500,
    color: "rgba(255, 255, 255, 0.6)",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "color 0.15s ease",
  },
};

export const setupModalStyles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: "#ffffff",
  },
  header: {
    textAlign: "center" as const,
    marginBottom: "24px",
  },
  title: {
    fontSize: "22px",
    fontWeight: 600,
    margin: "0 0 8px 0",
    color: "#ffffff",
  },
  subtitle: {
    fontSize: "14px",
    color: "rgba(255, 255, 255, 0.6)",
    margin: 0,
    lineHeight: 1.5,
    maxWidth: "280px",
  },
  methodSelector: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
    marginBottom: "24px",
  },
  methodButton: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "16px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    textAlign: "left" as const,
    width: "100%",
  },
  methodButtonSelected: {
    backgroundColor: "rgba(0, 152, 234, 0.15)",
    borderColor: "#0098EA",
  },
  methodIcon: {
    width: "48px",
    height: "48px",
    borderRadius: "12px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0098EA",
    flexShrink: 0,
  },
  methodContent: {
    flex: 1,
    minWidth: 0,
  },
  methodTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: "#ffffff",
    margin: "0 0 4px 0",
  },
  methodDescription: {
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.5)",
    margin: 0,
    lineHeight: 1.4,
  },
  continueButton: {
    width: "100%",
    padding: "14px 24px",
    fontSize: "16px",
    fontWeight: 600,
    color: "#ffffff",
    backgroundColor: "#0098EA",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "opacity 0.15s ease",
  },
  continueButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed" as const,
  },
  stepIndicator: {
    display: "flex",
    gap: "8px",
    marginBottom: "24px",
  },
  stepDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  stepDotActive: {
    backgroundColor: "#0098EA",
  },
};

export const unlockModalStyles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px",
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: "#ffffff",
  },
  biometricPrompt: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "32px",
    textAlign: "center" as const,
  },
  biometricIcon: {
    width: "80px",
    height: "80px",
    borderRadius: "20px",
    backgroundColor: "rgba(0, 152, 234, 0.15)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0098EA",
    marginBottom: "24px",
  },
  biometricTitle: {
    fontSize: "20px",
    fontWeight: 600,
    margin: "0 0 8px 0",
    color: "#ffffff",
  },
  biometricSubtitle: {
    fontSize: "14px",
    color: "rgba(255, 255, 255, 0.6)",
    margin: "0 0 24px 0",
  },
  usePinButton: {
    padding: "12px 24px",
    fontSize: "14px",
    fontWeight: 500,
    color: "#0098EA",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    transition: "opacity 0.15s ease",
  },
};


